### ISSUE TITLE
Support for 1.21.3

### ISSUE THREAD

**Issue by rradillen** [axieum/minecord#156]
### Is your feature request related to a problem?

When I run the current version om a minecraft 1.21.3 server it crashes on startup 'java.lang.NoSuchMethodError: 'net.minecraft.class_2168 net.minecraft.class_1297.method_5671'

### Describe the solution you'd like.

A compatible release.

### Describe alternatives you've considered.

Other mods that don't quite do the same this simply.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by axieum** [comment]
Hi, indeed. I did start to upgrade it, but got distracted playing the new Call of Duty BO6. 😅

I'll try to get to it soon!

**Comment by axieum** [comment]
Can you please try [`v2.1.0+1.21.3`](https://github.com/axieum/minecord/releases/tag/v2.1.0%2B1.21.3)? Sorry for the wait on getting this one updated.

**Comment by ErenKyojin** [comment]
Not done crazy tests but it works fine
