### ISSUE TITLE
`README.md` is missing newer `minecord-chat` messages

### ISSUE THREAD

**Issue by axieum** [axieum/minecord#60]
The [`README.md`](https://github.com/axieum/minecord/blob/main/README.md) needs updating to include the new Chat events relayed to and from Discord/Minecraft - these are found in the config class here:

https://github.com/axieum/minecord/blob/f90764ae0790d1d0069c49cd28b1d3b18eb2299c/minecord-chat/src/main/java/me/axieum/mcmod/minecord/impl/chat/config/ChatConfig.java#L44

https://github.com/axieum/minecord/blob/f90764ae0790d1d0069c49cd28b1d3b18eb2299c/minecord-chat/src/main/java/me/axieum/mcmod/minecord/impl/chat/config/ChatConfig.java#L133

The following unlisted events are:

* Discord events relayed to Minecraft
  * A user sent a message in reply to another
* Minecraft events relayed to Discord
  * A player sent an in-game message via the `/me` command
  * An admin broadcast an in-game message via the `/say` command
  * An admin broadcast an in-game message to all players via the `/tellraw @a` command

**Comment by Kaushik-Iyer** [comment]
Can I try to work on this?

**Comment by Kaushik-Iyer** [comment]
I think the Minecraft event of 'A player sent an in game message via the /me command' is already added to the README....
