### ISSUE TITLE
Unable to stop 'teleport' from sending messages

### ISSUE THREAD

**Issue by blurrednoise** [axieum/minecord#85]
### Expected behavior

to be able to disable teleport from sending messages when going through End or Nether portals

### Observed/actual behavior

Would always send a message even when removed

### Steps/models to reproduce

Try to remove teleport

### Version

2.0.1

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

I may be doing something wrong but I feel I have tried everything. If there is no way to remove it is there a way to have it send to its own channel?

**Comment by axieum** [comment]
Hi, you can set any of the messages you don't want to `"teleport": null,`.

Let me know how you go. 😊

**Comment by blurrednoise** [comment]
> Hi, you can set any of the messages you don't want to `null`, e.g. `"teleport": null,`.
> 
> Let me know how you go. 😊

Yep, this worked! Thanks!
Going to see how you did the Multi-Channel messages thanks for sending that as well.
