### ISSUE TITLE
Incompatible with Minecraft 1.19.0-1.19.3

### ISSUE THREAD

**Issue by JaxHendricks** [axieum/minecord#87]
### Expected behavior

Able to be used on 1.19.2

### Observed/actual behavior

Minecord requesting for 1.19.4 or 1.20+

### Steps/models to reproduce

Using a Quilt server running Version 1.19.2, insert the mod file, and run the server.

### Version

Server Version: 1.19.2 
Minecord Version: "Minecord v2.0.1+1.19.4"

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

![image](https://github.com/axieum/minecord/assets/112291260/793e9c28-743b-4a92-ab74-b141da37496e)
![image](https://github.com/axieum/minecord/assets/112291260/3f76924f-94e5-4baf-9842-14f52505a9a3)
![image](https://github.com/axieum/minecord/assets/112291260/46b6618d-ed53-4f64-80cf-2c44dd8f1965)

**Comment by axieum** [comment]
I have confirmed that the current `v2.0.1+1.19.4` built against 1.19.4 mappings does not function on `<=1.19.3`, sorry about that. For now, I've gone ahead and updated the compatible versions in Modrinth.

Is it possible for you to update to the latest Minecraft 1.19?

**Comment by JaxHendricks** [comment]
Currently, due to how my servers modpack is built out, mainly because some mods haven't been updated past 1.19.2. So we're sticking with 1.19.2.

I appreciate the response though.
